Optimization and fixes

diff --git a/rust-bevy/Makefile b/rust-bevy/Makefile
--- a/rust-bevy/Makefile
+++ b/rust-bevy/Makefile
@@ -6,7 +6,7 @@ default:
 
 .PHONY: run
 run: # run the program
-	nixVulkanIntel cargo run
+	nixVulkanIntel cargo run --features dev
 
 .PHONY: build
 build: # build to wasm
@@ -14,11 +14,11 @@ build: # build to wasm
 
 .PHONY: release
 release: # Build and publish a GitHub release with WASM
-    @if [ -z "$(VERSION)" ]; then \
-        echo "Error: VERSION is not set. Usage: make release VERSION=0.1.0"; \
-        exit 1; \
-    fi
-    wasm-pack build --release --target web
-    git tag v$(VERSION)
-    git push origin v$(VERSION)
-    gh release create v$(VERSION) pkg/* --title "v$(VERSION)" --notes "Release WASM build"
+	@if [ -z "$(VERSION)" ]; then \
+		echo "Error: VERSION is not set. Usage: make release VERSION=0.1.0"; \
+		exit 1; \
+	fi
+	wasm-pack build --release --target web
+	git tag v$(VERSION)
+	git push origin v$(VERSION)
+	gh release create v$(VERSION) pkg/* --title "v$(VERSION)" --notes "Release WASM build"
